# Generated by Django 4.2.9 on 2024-01-10 06:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ottapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adult_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy')], max_length=100)),
                ('release_date', models.DateField()),
                ('language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('malayalam', 'Malayalam'), ('tamil', 'Tamil'), ('kannada', 'Kannada'), ('telugu', 'Telugu'), ('bengali', 'Bengali')], max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('ratings', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('image', models.ImageField(upload_to='movie_image/')),
                ('image_cover', models.ImageField(upload_to='movie_images/')),
                ('video', models.FileField(upload_to='movie_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, validators=[ottapp.models.validate_name])),
                ('lastname', models.CharField(max_length=50, validators=[ottapp.models.validate_name])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True, validators=[ottapp.models.validate_username])),
                ('password', models.CharField(max_length=100)),
                ('DoB', models.DateField(validators=[ottapp.models.validate_dob])),
                ('phonenumber', models.CharField(max_length=15, validators=[ottapp.models.validate_phonenumber])),
            ],
        ),
        migrations.CreateModel(
            name='Kids_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy')], max_length=100)),
                ('release_date', models.DateField()),
                ('language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('malayalam', 'Malayalam'), ('tamil', 'Tamil'), ('kannada', 'Kannada'), ('telugu', 'Telugu'), ('bengali', 'Bengali')], max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('ratings', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('image', models.ImageField(upload_to='movie_image/')),
                ('image_cover', models.ImageField(upload_to='movie_images/')),
                ('video', models.FileField(upload_to='movie_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_months', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ottapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ottapp.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ottapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='KidsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ottapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Adult_WatchLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ottapp.adult_movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ottapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Adult_WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ottapp.adult_movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ottapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Adult_Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ottapp.adult_movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ottapp.userprofile')),
            ],
        ),
    ]
