# Generated by Django 4.2.9 on 2024-01-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult_movie',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='kids_movie',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
